### PR TITLE
Initital implementation of the https://github.com/mbrlabs/Mundus/issues/24

### PR DESCRIPTION
**Pull request by krukhlis**
This is initial implementation of the https://github.com/mbrlabs/Mundus/issues/24

ModelPlacementTool also contains the boolean property: shouldRespectTerrainSlope, default = true
This can be used to turn on and off the functionality.

### CODE REVIEW

**Comment by krukhlis** [comment]
Could you please push to the git your Eclipse formatter config?
So everyone willing to contribute will use the same rules? 
I've switched to the new Spring Tool Suite -- maybe they are using different rules by default comparing
to pure Eclipse. :(

**Comment by mbrlabs** [comment]
Yes i will do that. For now you can use the libGDX formatter https://github.com/libgdx/libgdx/blob/master/eclipse-formatter.xml ;)

**Comment by krukhlis** [comment]
Cool, I've fixed formatting using libgdx formatter. Hope, now it's easier to check difference.
I've decided to go with the new commit for the formatting just in case.

**Comment by mbrlabs** [comment]
Yes thanks, it's better. Still a lot of changes, because i use the IntelliJ defaults.
I really need to set up the formatter

**Pull request merged**
