### PR TITLE
Scaling tool, first version

### PR DESCRIPTION
**Pull request by codenigma**
- scaling tool for x,y,z scaling
- undo/redo of scaling not implemented yet
- issue: scaling in xyz will reset previous values

### CODE REVIEW

**Comment by mbrlabs** [comment]
Not bad for a first version. Can you fix the issues before i merge it?
The handles are also a bit weird...especially if the model is really big. You could use the arrow handles from the `TransformTool` for now. Ideally it should look like [this](https://docs.unity3d.com/410/Documentation/Images/manual/Transforms-3.jpg), but arrows are ok too.

**Comment by codenigma** [comment]
That issue was a hard one :/

Scaling of tool is not fixed. There is a problem:

The method gameObjectSelected() is never called. So i can't scale the handles.
I looked in translateTool it where it is working and called.
I don't get the point why it is not working ...

**Comment by mbrlabs** [comment]
Hmm, that's strange. I did a quick test, and it gets called. 
Switching between tools is still a bit messy, because it always defaults to the TranslateTool if no tool is selected.

1. Click ESC to reset your current tool. 
2. Select the scale tool
3. Right click on the object.
4. gameObjectSelected() in the scale tool will be called (once)

**Comment by codenigma** [comment]
AHH. Ok i always used the outline. Learned something new :-)
It will not be called if the user only uses the outline to select the object.

**Comment by mbrlabs** [comment]
That's good. This is how we discover bugs and un-userfriendly ux ;)
I'll create a issue for that.

**Comment by mbrlabs** [comment]
Pretty nice, thanks!

**Pull request merged**
